### ISSUE TITLE
Uncaught Error: listen EADDRINUSE /tmp/haskell-debug.sock

### ISSUE THREAD

**Issue by lwdye** [atom-haskell/haskell-debug#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [haskell-debug](https://github.com/atom-haskell/haskell-debug) package 0.3.4

### Stack Trace

Uncaught Error: listen EADDRINUSE /tmp/haskell-debug.sock

```
At events.js:160

Error: listen EADDRINUSE /tmp/haskell-debug.sock
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1382:7)
    at /packages/haskell-debug/lib/TerminalReporter.js:27:21)
    at /packages/haskell-debug/lib/Debugger.js:28:33)
    at /packages/haskell-debug/lib/main.js:30:28)
    at Generator.next (<anonymous>)
    at fulfilled (/packages/haskell-debug/lib/main.js:4:58)
```

### Commands

```
     -0:45.5.0 editor:newline (input.hidden-input)
     -0:38.9.0 core:copy (input.hidden-input)
     -0:37.2.0 editor:newline (input.hidden-input)
     -0:36.7.0 core:paste (input.hidden-input)
     -0:36.1.0 editor:newline (input.hidden-input)
     -0:35.6.0 core:paste (input.hidden-input)
     -0:35.2.0 editor:newline (input.hidden-input)
     -0:34.7.0 core:paste (input.hidden-input)
     -0:34.4.0 editor:newline (input.hidden-input)
     -0:34 core:paste (input.hidden-input)
     -0:32.9.0 core:save (input.hidden-input)
     -0:28.4.0 command-palette:toggle (input.hidden-input)
     -0:25.4.0 core:backspace (input.hidden-input)
     -0:22.5.0 haskell:debug (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-haskell 0.4.0 
atom-json-editor 0.4.1 
autocomplete-haskell 1.0.1 
busy-signal 1.4.3 
haskell-debug 0.3.4 
haskell-ghc-mod 2.1.3 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
haskell-pointfree 0.2.0 
haskell-scry 1.0.7 
hasklig 0.4.0 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.5 
ide-haskell-hasktags 0.0.12 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.7.8 
import-sf-mono 1.0.1 
intentions 1.1.5 
language-haskell 1.15.0 
language-haskell-scoped 0.1.0 
language-mathematica 0.3.2 
linter 2.2.0 
linter-hlint 2.0.0 
linter-ui-default 1.6.10 
react 0.17.0 
script 3.17.3 
```

**Comment by lierdakil** [comment]
Yeah... something crashed apparently. I've been meaning to take a look a this, but never got anywhere, mostly due to lack of time. Remove `/tmp/haskell-debug.sock` manually.
